services:
  app:
    build:
      context: .
    environment:
      PORT: ${PORT}
    env_file:
      - ./.env
    ports:
      - 7000:7000
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-2
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention=1d'
      - '--storage.tsdb.wal-compression'
      - --web.enable-lifecycle
      - --web.listen-address=:9010

    expose:
      - 9010
    ports:
      - 9010:9010

volumes:
  prometheus_data:
